local Language = {}
local function isVietnamese()
    local LocalizationService = game:GetService("LocalizationService")
    local player = game:GetService("Players").LocalPlayer
    local success, countryCode = pcall(function()
        return LocalizationService:GetCountryRegionForPlayerAsync(player)
    end)
    return success and countryCode == "VN"
end
Language.isVN = isVietnamese()
Language.vi = {
    ["Bacon Hub"] = "Bacon Hub",
    ["Main"] = "Chính",
    ["Farm"] = "Farm",
    ["Status"] = "Trạng Thái",
    ["Combat"] = "Chiến Đấu",
    ["Stats"] = "Chỉ Số",
    ["Teleport"] = "Dịch Chuyển",
    ["Devil Fruit"] = "Trái Ác Quỷ",
    ["Shop"] = "Cửa Hàng",
    ["Misc"] = "Khác",
    ["Player"] = "Người Chơi",
    ["Discord"] = "Discord",
    ["Select Weapon"] = "Chọn Vũ Khí",
    ["Auto Farm Level"] = "Tự Động Farm Cấp",
    ["Auto Farm Boss"] = "Tự Động Farm Boss",
    ["Auto Farm Mastery"] = "Tự Động Farm Thành Thạo",
    ["Select Farm Boss"] = "Chọn Boss Để Farm",
    ["Auto Farm Bone"] = "Tự Động Farm Xương",
    ["Auto Farm Cake Prince"] = "Tự Động Farm Hoàng Tử Bánh",
    ["Auto Farm Dough King"] = "Tự Động Farm Vua Bột",
    ["Race"] = "Chủng Tộc",
    ["Level"] = "Cấp Độ",
    ["Fragments"] = "Mảnh",
    ["Beli"] = "Beli",
    ["Devil Fruit"] = "Trái Ác Quỷ",
    ["Status Information"] = "Thông Tin Trạng Thái",
    ["Melee"] = "Cận Chiến",
    ["Defense"] = "Phòng Thủ",
    ["Sword"] = "Kiếm",
    ["Gun"] = "Súng",
    ["Fruit"] = "Trái",
    ["Auto Farm Mastery Gun"] = "Tự Động Farm Thành Thạo Súng",
    ["Auto Farm Mastery Devil Fruit"] = "Tự Động Farm Thành Thạo Trái",
    ["Auto Farm Mastery Sword"] = "Tự Động Farm Thành Thạo Kiếm",
    ["Mob Mastery"] = "Farm Quái",
    ["Auto Farm BF Mastery"] = "Tự Động Farm Thành Thạo Trái",
    ["Auto Stats Melee"] = "Tự Động Cộng Cận Chiến",
    ["Auto Stats Defense"] = "Tự Động Cộng Phòng Thủ",
    ["Auto Stats Sword"] = "Tự Động Cộng Kiếm",
    ["Auto Stats Gun"] = "Tự Động Cộng Súng",
    ["Auto Stats Devil Fruit"] = "Tự Động Cộng Trái Ác Quỷ",
    ["Point Stats"] = "Điểm Chỉ Số",
    ["Auto Stats Kaitun"] = "Tự Động Cộng Điểm Kaitun",
    ["World"] = "Thế Giới",
    ["Island"] = "Đảo",
    ["Select World"] = "Chọn Thế Giới",
    ["Select Island"] = "Chọn Đảo",
    ["Teleport to Island"] = "Dịch Chuyển Đến Đảo",
    ["World 1"] = "Thế Giới 1",
    ["World 2"] = "Thế Giới 2",
    ["World 3"] = "Thế Giới 3",
    ["Auto Random Fruit"] = "Tự Động Quay Trái",
    ["Auto Store Fruit"] = "Tự Động Cất Trái",
    ["Bring All Fruit"] = "Lấy Tất Cả Trái",
    ["Teleport to Fruit"] = "Dịch Chuyển Đến Trái",
    ["Auto Eat Fruit"] = "Tự Động Ăn Trái",
    ["Auto Drop Fruit"] = "Tự Động Vứt Trái",
    ["Buy Abilities"] = "Mua Kỹ Năng",
    ["Buy Items"] = "Mua Vật Phẩm",
    ["Buy All Swords"] = "Mua Tất Cả Kiếm",
    ["Fighting Style"] = "Phong Cách Chiến Đấu",
    ["Ability Teacher"] = "Thầy Dạy Kỹ Năng",
    ["Buy Haki"] = "Mua Haki",
    ["Buy Geppo"] = "Mua Geppo",
    ["Buy Buso Haki"] = "Mua Buso Haki",
    ["Buy Soru"] = "Mua Soru",
    ["Buy Observation Haki"] = "Mua Haki Quan Sát",
    ["Server"] = "Máy Chủ",
    ["Codes"] = "Mã Code",
    ["Remove Fog"] = "Xóa Sương Mù",
    ["Remove Damage"] = "Xóa Hiệu Ứng Damage",
    ["White Screen"] = "Màn Hình Trắng",
    ["Auto Redeem All Codes"] = "Tự Động Nhập Tất Cả Mã",
    ["Rejoin Server"] = "Vào Lại Máy Chủ",
    ["Hop Server"] = "Đổi Máy Chủ",
    ["Boost FPS"] = "Tăng FPS",
    ["Anti AFK"] = "Chống AFK",
    ["Enable PvP"] = "Bật PvP",
    ["Auto Active Race"] = "Tự Động Kích Hoạt Chủng Tộc",
    ["Auto Dodge"] = "Tự Động Né",
    ["Auto Camera Player"] = "Tự Động Nhìm Người Chơi",
    ["Speed Run Player"] = "Tăng Tốc Chạy",
    ["Dash no Cd"] = "Lướt Không Hồi Chiêu",
    ["Inf Soru"] = "Soru Vô Hạn",
    ["Inf Geppo"] = "Geppo Vô Hạn",
    ["No Clip"] = "Xuyên Tường",
    ["Walk On Water"] = "Đi Trên Nước",
    ["Fly"] = "Bay",
    ["Fly Speed"] = "Tốc Độ Bay",
    ["Enabled"] = "Đã Bật",
    ["Disabled"] = "Đã Tắt",
    ["Loading"] = "Đang Tải",
    ["Success"] = "Thành Công",
    ["Failed"] = "Thất Bại",
    ["Select"] = "Chọn",
    ["None"] = "Không",
    ["Auto"] = "Tự Động",
    ["Manual"] = "Thủ Công",
    ["Speed"] = "Tốc Độ",
    ["Distance"] = "Khoảng Cách",
    ["Position"] = "Vị Trí",
    ["Teleported to"] = "Đã dịch chuyển đến",
    ["Enabled successfully"] = "Đã bật thành công",
    ["Disabled successfully"] = "Đã tắt thành công",
    ["Please wait"] = "Vui lòng đợi",
    ["Quest completed"] = "Hoàn thành nhiệm vụ",
    ["Boss defeated"] = "Đã đánh bại Boss",
}
function Language:T(text)
    if self.isVN and self.vi[text] then
        return self.vi[text]
    end
    return text
end
function Language:t(text)
    return self:T(text)
end
return Language
